
CREATE DATABASE IF NOT EXISTS JifferDB;
USE JifferDB;
CREATE TABLE IF NOT EXISTS gifs(uuid CHAR(36) NOT NULL PRIMARY KEY, name VARCHAR(50), path VARCHAR(100), featured TINYINT, creationDate DATE, processing TINYINT )